### ISSUE TITLE
The services do not run on default ports on rooted devices - version 2.0.0

### ISSUE THREAD

**Issue by sastry17** [aau-network-security/HosTaGe#49]
The services run on non-default ports even on rooted devices.

**Comment by irinil** [comment]
Hi @sastry17,
I rooted my emulator Nexus 4 API 25 X86 and the redirection of the ports works correctly as you can see below:

![2020-07-07 15_00_35-Window](https://user-images.githubusercontent.com/16364949/86780703-b2126000-c065-11ea-94be-884a173ee809.png)

I also performed an attack using the emulator feature adb forward for the ftp port from the redirect-ports.sh script.

 
![2020-07-07 15_24_33-Window](https://user-images.githubusercontent.com/16364949/86781028-10d7d980-c066-11ea-8b5a-36f14a140c88.png)

![2020-07-07 15_11_02-Window](https://user-images.githubusercontent.com/16364949/86781050-159c8d80-c066-11ea-902f-64d8f124fa8c.png)

![2020-07-07 15_06_32-Window](https://user-images.githubusercontent.com/16364949/86781067-1a614180-c066-11ea-8260-61f2be1426f9.png)

The only problem was that the "Porthack" check caused an error and didn't let the port redirection to continue. Therefore, I had to comment the methods for the "Porthack" temporarily in order to have the redirection working.
In your rooted phone porthack works correctly? If it doesn't then I will commit the changes disabling the porthack temporarily or removing it if you want me to.

**Comment by sastry17** [comment]
Hi @irinil 

I have sent you a screen recording of my phone (in Teams). There are some issues.  

1. The app does not detect that the device is rooted on the first launch. I have to go back to the home screen and then to the settings again to see that the device is identified to be rooted.
2. After the app detects that the phone is rooted, some services are running on non-default ports. After the restart the services, the ports change in random. 
3. The app crashes on stop/start of some services (as seen in the video)

**Comment by sastry17** [comment]
This issue is solved. The services start on default ports on rooted devices.
